{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-crayon
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/crayon_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/crayon/crayon_{{ version }}.tar.gz
  sha256: 44122cafddcd8a35176b2a6bcab10c5f81cd5440d9e29d20091b31a0ef647954

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('crayon')"           # [not win]
    - "\"%R%\" -e \"library('crayon')\""  # [win]

about:
  home: https://github.com/r-lib/crayon#readme
  license: MIT
  summary: Colored terminal output on terminals that support 'ANSI' color and highlight codes. It also works in 'Emacs' 'ESS'. 'ANSI' color support is automatically detected. Colors and highlighting can be combined and nested. New styles can also be created easily. This package was inspired by the 'chalk' 'JavaScript' project.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
