appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: B7EHUNEBtrG3l3bVF89tyq7mO2Xy0vE5PRD/4cgSIWDzdjcNCfyIR5EdRvoNCozmR5+9IGL4J4BZTg1qg2q5IEmaJ3FsNkJG5xB8y493QDzRrtO3gF36Say92Y3o2OIDZ1D1rNB6C0h1G41bDDWlFLVOxHUk+RtueUdshhLjEKtdgpE33x462KTpGwLyGTXhzBnB8X9h/J3rCPxxnyzD8Yewb5m+WUCoiIpTN/5gKVpbtmBp2hHuVxaX0M493Y4ly65oNt8MHQ+I+P7T84VcMY2dvekbQ2cJaUUucKOyyMwwycGl+pb1yNm9Emmw+20ynco6ExYWrU0Ss/QR0NF1s/WZC2g4ZgtjiIDxlD1TkYZDYKTopBQqTzm8H1xYOQWRXDp6hVhQ1HxYNVlqIN6cHUfMUNn9ORHb8QZ66ijyQa/Mw5ssoKNkqcKAWI0cbHEAd9Zq5znghl0m69Y/xCsgv4IlTHM8lpNgiw39TQBrG4Tl4TaJJfKdJIENBt5MIam8kTqMf8N/YO17TTHtbt+M1N1dGOujwg71ObRHfHndIHjhpNqQDwG7XfHUF8LYFpukuzkRHmPDOlOxWNLuf9u7Ka9T/DL/CVJgeNBkcnvx9bTYJ1qEsTbvXptHTcnF8sr6yjUAuYweLPlIEzPChJFB7SPrImlKN88TgLW7QrGkKBA=}
